sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.26.0
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
      && tar -xzvf SDL2-2.0.5.tar.gz
      && pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi
