[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.5.1"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]

edition = "2018"
license = "MIT"
readme = "README.md"
categories = ["game-engines"]
build = "build.rs"
exclude = ["resources", "!LiberationMono-Regular.ttf"]

[badges]
maintenance = { status = "passively-maintained" }

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
default = ["c_dependencies"]
bzip2 = ["zip/bzip2"]
mp3 = ["rodio/mp3"]
multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]
c_dependencies = ["bzip2", "mp3"]

[dependencies]
bitflags = "1"
zip = { version = "0.5", default-features = false }
directories = "2"
gfx = "0.18"
gfx_core = "0.9"
gfx_device_gl = "0.16"
glyph_brush = "0.6"
gfx_window_glutin = "0.31"
glutin = "0.21"
winit = { version = "0.19.3" }
image = {version = "0.23", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm",
"tga", "tiff", "webp", "bmp", "dxt", ] }
rodio = { version = "0.10", default-features = false, features = ["flac", "vorbis", "wav"] }
serde = "1"
serde_derive = "1"
toml = "0.5"
log = "0.4"
lyon = "0.14"
smart-default = "0.5"
nalgebra = {version = "0.18", features = ["mint"]}
# Has to be the same version of mint that our math lib uses here.
mint = "0.5"
gilrs = "0.7"
approx = "0.3"

[dev-dependencies]
chrono = "0.4"
fern = "0.5"
oorandom = "11"
structopt = "0.3"
glam = { version = "0.8", features = ["mint"]}

skeptic = "0.13"
getrandom = "0.1"

[build-dependencies]
skeptic = "0.13"

