[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.5.0-rc.2"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]

edition = "2018"
license = "MIT"
readme = "README.md"
categories = ["game-engines"]
build = "build.rs"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
default = ["c_dependencies"]
bzip2 = ["zip/bzip2"]
mp3 = ["rodio/mp3"]
multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]
c_dependencies = ["bzip2", "mp3"]

[dependencies]
bitflags = "1.0"
zip = { version = "0.5", default-features = false }
directories = "1.0.2"
gfx = "0.18"
gfx_core = "0.9"
gfx_device_gl = "0.16"
glyph_brush = "0.4"
gfx_window_glutin = "0.30"
glutin = "0.20"
winit = { version = "0.19" }
image = {version = "0.21", default-features = false, features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm",
"tga", "tiff", "webp", "bmp", "dxt", ] }
rodio = { version = "0.8", default-features = false, features = ["flac", "vorbis", "wav"] }
serde = "1"
serde_derive = "1"
toml = "0.5"
log = "0.4"
lyon = "0.13"
smart-default = "0.5"
nalgebra = {version = "0.18", features = ["mint"] }
# Has to be the same version of mint that nalgebra uses here.
mint = "0.5"
gilrs = "0.7"
approx = "0.3"

[dev-dependencies]
chrono = "0.4"
fern = "0.5"
rand = "0.6"
structopt = "0.2"
cgmath = { version = "0.17", features = ["mint"]}
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"

