[package]
name = "ggez"
description = "Rust library to create a Good Game Easily"
version = "0.3.3"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]
license = "MIT"
readme = "README.md"
categories = ["game-engines"]

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
# If this feature is enabled, it will add <cargo root dir>/resources/ to
# the resource search path.
cargo-resource-root = []

[profile.dev]
codegen-units=4



[dependencies]
rusttype = "0.2"
rand = "0.3"
zip = "0.1"
app_dirs = "1.1"
gfx = "0.15"
gfx_device_gl = "0.14"
gfx_window_sdl = "0.6"
image = "0.12"
sdl2 = "0.29"
rodio = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
lyon = "0.4.1"
mint = { version = "0.4", optional = true }

[dev-dependencies]
cgmath = "0.14"
