[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.8.0-rc0"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]

edition = "2021"
license = "MIT"
readme = "README.md"
categories = ["game-engines"]
build = "build.rs"
exclude = ["docs", "resources", "!LiberationMono-Regular.ttf"]

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
default = ["c_dependencies", "audio", "gamepad"]
zip-compression = ["zip/bzip2", "zip/zstd"]
mp3 = ["rodio/mp3"]
multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]
c_dependencies = ["zip-compression", "mp3"]
audio = ["rodio"]
gamepad = ["gilrs"]

[dependencies]
bitflags = "1"
zip = { version = "0.6", default-features = false, features = ["deflate"]  }
directories = "4.0.1"
wgpu = "0.12"
glyph_brush = "0.7"
winit = "0.26"
image = { version = "0.24", default-features = false, features = [
   "gif",
   "png",
   "pnm",
   "tga",
   "tiff",
   "webp",
   "bmp",
   "dxt",
] }
rodio = { version = "0.15", optional = true, default-features = false, features = [
   "flac",
   "vorbis",
   "wav",
] }
serde = "1"
serde_derive = "1"
toml = "0.5"
log = "0.4"
lyon = "0.17"
smart-default = "0.6"
glam = { version = "0.20", features = ["mint"] }
# Has to be the same version of mint that our math lib uses here.
mint = "0.5"
gilrs = { version = "0.8", optional = true }
approx = "0.5"
bytemuck = "1.7"
pollster = "0.2"
memoffset = "0.6"
crevice = "0.8"
typed-arena = "2.0"
lazy_static = "1.4"
futures = "0.3"
ordered-float = "2.10"

[dev-dependencies]
chrono = "0.4"
fern = "0.6"
oorandom = "11"
argh = "0.1"
rand = "0.8"
keyframe = "1"
keyframe_derive = "1"
num-traits = "0.2"
num-derive = "0.3"

skeptic = "0.13"
getrandom = "0.2"

[build-dependencies]
skeptic = "0.13"
