[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.4.1"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]
license = "MIT"
readme = "README.md"
categories = ["game-engines"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
# If this feature is enabled, it will add <cargo root dir>/resources/ to
# the resource search path.
cargo-resource-root = []
bzip2 = ["zip/bzip2"]
use-log-crate = ["log"]
default = ["bzip2"]

[dependencies]
rusttype = "0.3"
zip = { version = "0.3", default-features = false }
app_dirs2 = "2"
gfx = "0.17"
gfx_device_gl = "0.15"
gfx_window_sdl = "0.8"
image = "0.18"
sdl2 = "0.31"
rodio = "0.5"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
lyon = "0.10"
log = { version = "0.4", optional = true }
smart-default = "0.2"
nalgebra = "0.14"

[dev-dependencies]
rand = "0.3"
clap = "2"
