[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.4.4"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]
license = "MIT"
readme = "README.md"
categories = ["game-engines"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "ggez"
path = "src/lib.rs"

[features]
# If this feature is enabled, it will add <cargo root dir>/resources/ to
# the resource search path.
cargo-resource-root = []
bzip2 = ["zip/bzip2"]
default = ["bzip2"]
mint = ["nalgebra/mint"]
multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]

[dependencies]
rusttype = "0.5"
zip = { version = "0.3", default-features = false }
app_dirs2 = "2"
gfx = "0.17"
gfx_device_gl = "0.15"
gfx_glyph = "~0.10.2"
gfx_window_sdl = "0.8"
image = {version = "0.19", default-features = false, features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm",
"tga", "tiff", "webp", "bmp", "dxt", ] }
sdl2 = "0.31"
rodio = "0.7"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
log = "0.4"
lyon = "0.10"
smart-default = "0.2"
nalgebra = "0.14"

[dev-dependencies]
chrono = "0.4"
fern = "0.5"
rand = "0.4"
clap = "2"
